# The propose of this workflow is to check the code before merge to main branch

name: check code style and buildable

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup pre-commit and Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Test Buildable
        run: bun run build
